In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [23]:
import date_calculator as dc

In [65]:
report = [0 for i in range(3)]
for i in range(3):
    report[i] = pd.read_excel('Report ('+str(i)+').csv')

In [21]:
report[0]

,요일구분,기준년도,2014년,2014년.1,2014년.2,2014년.3,2014년.4,2014년.5,2014년.6,2014년.7,2014년.8
0,요일구분,기준년도,합계,20세이하,21세이상~30세이하,31세이상~40세이하,41세이상~50세이하,51세이상~60세이하,61세이상~64세이하,65세이상,미분류
1,합계,발생건수,9960,426,1346,2046,2377,1944,360,653,808
2,합계,구성비(%),100,4.3,13.5,20.5,23.9,19.5,3.6,6.6,8.1
3,합계,사망자수,52,0,7,9,13,13,3,7,0
4,합계,부상자수,16674,702,2307,3492,3909,3104,578,942,1640
5,합계,중상자수,1604,67,232,316,352,328,91,148,70
6,합계,경상자수,9002,348,1193,1840,2151,1716,301,540,913
7,합계,부상신고자수,6068,287,882,1336,1406,1060,186,254,657
8,수요일,발생건수,2017,103,328,420,444,372,81,100,169
9,수요일,구성비(%),100,5.1,16.3,20.8,22,18.4,4,5,8.4
10,수요일,사망자수,17,0,4,5,1,4,1,2,0
11,수요일,부상자수,4087,191,684,867,965,692,147,149,392
12,수요일,중상자수,393,17,78,86,88,78,21,16,9
13,수요일,경상자수,2157,109,334,457,512,374,87,93,191
14,수요일,부상신고자수,1537,65,272,324,365,240,39,40,192
15,목요일,발생건수,2695,102,316,561,639,549,99,209,220
16,목요일,구성비(%),100,3.8,11.7,20.8,23.7,20.4,3.7,7.8,8.2
17,목요일,사망자수,14,0,1,2,4,3,2,2,0
18,목요일,부상자수,4084,151,466,854,957,802,142,287,425
19,목요일,중상자수,386,15,37,71,81,83,26,45,28
20,목요일,경상자수,2174,62,248,453,515,426,71,155,244
21,목요일,부상신고자수,1524,74,181,330,361,293,45,87,153
22,금요일,발생건수,2729,111,343,567,687,526,90,197,208
23,금요일,구성비(%),100,4.1,12.6,20.8,25.2,19.3,3.3,7.2,7.6
24,금요일,사망자수,13,0,0,2,4,5,0,2,0
25,금요일,부상자수,4180,170,519,886,1011,818,139,270,367
26,금요일,중상자수,438,17,52,83,93,89,32,51,21
27,금요일,경상자수,2303,77,293,454,578,480,55,152,214
28,금요일,부상신고자수,1439,76,174,349,340,249,52,67,132
29,토요일,발생건수,2519,110,359,498,607,497,90,147,211
30,토요일,구성비(%),100,4.4,14.3,19.8,24.1,19.7,3.6,5.8,8.4
31,토요일,사망자수,8,0,2,0,4,1,0,1,0
32,토요일,부상자수,4323,190,638,885,976,792,150,236,456
33,토요일,중상자수,387,18,65,76,90,78,12,36,12
34,토요일,경상자수,2368,100,318,476,546,436,88,140,264
35,토요일,부상신고자수,1568,72,255,333,340,278,50,60,180
36,출처) 도로교통공단.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [17]:
report[0]['요일구분'] == '수요일'

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8      True
9      True
10     True
11     True
12     True
13     True
14     True
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
30    False
31    False
32    False
33    False
34    False
35    False
36    False
Name: 요일구분, dtype: bool

In [67]:
report[1]['date'] = '0'
tmp1 = report[1].where(report[1]['요일구분'] == '수요일').dropna()['date']

tmp1 = pd.Series([dc.date_calculate('20140101', 8 * 1)], tmp1.index)
tmp1

29    20140108
30    20140108
31    20140108
32    20140108
33    20140108
34    20140108
35    20140108
dtype: object

In [69]:
series1 = pd.Series([dc.date_calculate('20140101', 8 * 1)], report[1].where(report[1]['요일구분'] == '수요일').dropna()['date'].index)
series2 = pd.Series([dc.date_calculate('20140102', 8 * 1)], report[1].where(report[1]['요일구분'] == '목요일').dropna()['date'].index)
pd.concat([series1, series2], axis = 0)

29    20140108
30    20140108
31    20140108
32    20140108
33    20140108
34    20140108
35    20140108
36    20140109
37    20140109
38    20140109
39    20140109
40    20140109
41    20140109
42    20140109
dtype: object

In [54]:
report[1]

,요일구분,기준년도,2014년,2014년.1,2014년.2,2014년.3,2014년.4,2014년.5,2014년.6,2014년.7,2014년.8,date
0,요일구분,기준년도,합계,20세이하,21세이상~30세이하,31세이상~40세이하,41세이상~50세이하,51세이상~60세이하,61세이상~64세이하,65세이상,미분류,0
1,합계,발생건수,18561,743,2436,4013,4303,3628,712,1147,1579,0
2,합계,구성비(%),100,4,13.1,21.6,23.2,19.5,3.8,6.2,8.5,0
3,합계,사망자수,102,1,14,18,25,32,2,9,1,0
4,합계,부상자수,29085,1106,3776,6579,6686,5328,1060,1604,2946,0
5,합계,중상자수,2846,86,345,562,701,602,176,239,135,0
6,합계,경상자수,15581,588,2010,3369,3624,2920,581,849,1640,0
7,합계,부상신고자수,10658,432,1421,2648,2361,1806,303,516,1171,0
8,일요일,발생건수,1788,96,274,403,324,368,62,111,150,0
9,일요일,구성비(%),100,5.4,15.3,22.5,18.1,20.6,3.5,6.2,8.4,0
10,일요일,사망자수,7,0,1,2,2,1,0,1,0,0
11,일요일,부상자수,3226,168,474,799,551,640,95,179,320,0
12,일요일,중상자수,306,6,45,77,64,62,11,28,13,0
13,일요일,경상자수,1691,92,236,358,308,346,64,108,179,0
14,일요일,부상신고자수,1229,70,193,364,179,232,20,43,128,0
15,월요일,발생건수,2874,126,336,604,683,576,131,178,240,0
16,월요일,구성비(%),100,4.4,11.7,21,23.8,20,4.6,6.2,8.4,0
17,월요일,사망자수,16,0,1,4,1,7,0,3,0,0
18,월요일,부상자수,4236,173,501,914,1022,795,190,227,414,0
19,월요일,중상자수,403,10,55,60,100,89,29,32,28,0
20,월요일,경상자수,2253,109,259,470,536,422,109,117,231,0
21,월요일,부상신고자수,1580,54,187,384,386,284,52,78,155,0
22,화요일,발생건수,2570,103,343,574,611,476,87,157,219,0
23,화요일,구성비(%),100,4,13.3,22.3,23.8,18.5,3.4,6.1,8.5,0
24,화요일,사망자수,12,0,1,0,6,5,0,0,0,0
25,화요일,부상자수,3821,168,512,845,899,676,123,218,380,0
26,화요일,중상자수,376,16,44,72,92,69,24,39,20,0
27,화요일,경상자수,2043,84,296,441,463,389,63,111,196,0
28,화요일,부상신고자수,1402,68,172,332,344,218,36,68,164,0
29,수요일,발생건수,2761,91,325,583,700,533,121,147,261,0
30,수요일,구성비(%),100,3.3,11.8,21.1,25.4,19.3,4.4,5.3,9.5,0
31,수요일,사망자수,19,1,4,1,3,5,1,3,1,0
32,수요일,부상자수,4230,119,493,904,1057,786,182,210,479,0
33,수요일,중상자수,437,14,43,88,114,91,34,32,21,0
34,수요일,경상자수,2233,46,235,458,579,447,94,114,260,0
35,수요일,부상신고자수,1560,59,215,358,364,248,54,64,198,0
36,목요일,발생건수,2771,89,354,616,644,561,104,194,209,0
37,목요일,구성비(%),100,3.2,12.8,22.2,23.2,20.2,3.8,7,7.5,0
38,목요일,사망자수,18,0,4,2,6,3,1,2,0,0
39,목요일,부상자수,4182,119,517,924,1031,782,148,280,381,0
40,목요일,중상자수,396,8,47,76,97,94,25,39,10,0
41,목요일,경상자수,2278,64,263,478,563,440,84,149,237,0
42,목요일,부상신고자수,1508,47,207,370,371,248,39,92,134,0
43,금요일,발생건수,3043,113,419,647,732,588,110,180,254,0
44,금요일,구성비(%),100,3.7,13.8,21.3,24.1,19.3,3.6,5.9,8.3,0
45,금요일,사망자수,10,0,1,3,2,4,0,0,0,0
46,금요일,부상자수,4518,175,601,995,1093,831,169,232,422,0
47,금요일,중상자수,445,13,52,81,124,97,32,29,17,0
48,금요일,경상자수,2413,102,331,513,605,443,86,118,215,0
49,금요일,부상신고자수,1660,60,218,401,364,291,51,85,190,0
50,토요일,발생건수,2754,125,385,586,609,526,97,180,246,0
51,토요일,구성비(%),100,4.5,14,21.3,22.1,19.1,3.5,6.5,8.9,0
52,토요일,사망자수,20,0,2,6,5,7,0,0,0,0
53,토요일,부상자수,4872,184,678,1198,1033,818,153,258,550,0
54,토요일,중상자수,483,19,59,108,110,100,21,40,26,0
55,토요일,경상자수,2670,91,390,651,570,433,81,132,322,0
56,토요일,부상신고자수,1719,74,229,439,353,285,51,86,202,0
57,출처) 도로교통공단.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0

In [80]:
for i in (1,2):
    report[i]['date'] = 0
    series1 = pd.Series([dc.date_calculate('20140101', 8 * i)], report[i].where(report[i]['요일구분'] == '수요일').dropna()['date'].index)
    series2 = pd.Series([dc.date_calculate('20140102', 8 * i)], report[i].where(report[i]['요일구분'] == '목요일').dropna()['date'].index)
    series3 = pd.Series([dc.date_calculate('20140103', 8 * i)], report[i].where(report[i]['요일구분'] == '금요일').dropna()['date'].index)
    series4 = pd.Series([dc.date_calculate('20140104', 8 * i)], report[i].where(report[i]['요일구분'] == '토요일').dropna()['date'].index)
    series5 = pd.Series([dc.date_calculate('20140105', 8 * i)], report[i].where(report[i]['요일구분'] == '일요일').dropna()['date'].index)
    series6 = pd.Series([dc.date_calculate('20140106', 8 * i)], report[i].where(report[i]['요일구분'] == '월요일').dropna()['date'].index)
    series7 = pd.Series([dc.date_calculate('20140107', 8 * i)], report[i].where(report[i]['요일구분'] == '화요일').dropna()['date'].index)

    all_series = pd.concat([series1, series2, series3, series4, series5, series6, series7], axis=0)
    report[i]['date'] = all_series

dfa = report[1].dropna().sort_values(['date'])
#dfa[('date', '2014년')]

KeyError: ('date', '2014년')