In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
import os
import glob

In [3]:
Week_2014 = [[4,7,7,7,6],[1,7,7,7,6],[1,7,7,7,7,2],[5,7,7,7,4],[3,7,7,7,7],
            [7,7,7,7,2],[5,7,7,7,5],[2,7,7,7,7,1],[6,7,7,7,3],[4,7,7,7,6],
            [1,7,7,7,7,1],[6,7,7,7,4]]
Week_2015 = [[3,7,7,7,7],[7,7,7,7],[7,7,7,7,3],[4,7,7,7,5],[2,7,7,7,7,1],
            [6,7,7,7,3],[4,7,7,7,6],[1,7,7,7,7,2],[5,7,7,7,4],[3,7,7,7,7],
             [7,7,7,7,2],[5,7,7,7,5]]
Week_2016 = [[2,7,7,7,7,1],[6,7,7,7,2],[5,7,7,7,5],[2,7,7,7,7],[7,7,7,7,3],
         [4,7,7,7,5],[2,7,7,7,7,1],[6,7,7,7,4],[3,7,7,7,6],[1,7,7,7,7,2],
        [5,7,7,7,4],[3,7,7,7,7]]
Years = [Week_2014, Week_2015, Week_2016]

Days = ['일요일','월요일','화요일','수요일','목요일','금요일','토요일']

In [4]:
def save(name, DF):
    writer = pd.ExcelWriter(name+'.xlsx')
    DF.to_excel(writer,'Sheet1')
    writer.save()

In [5]:
def prettydate(year,month,date):
    if month < 10:
        m_tmp = str(0)+str(month)
    else:
        m_tmp = str(month)
    if date < 10:
        d_tmp = str(0)+str(date)
    else:
        d_tmp = str(date)
    return str(year)+m_tmp+d_tmp

In [6]:
def day2date(year, month, week, day):
    month_exam = Years[year-2014][month-1]
    date = 0
    week_exam = 0
    for week_len in month_exam:
        week_exam += 1
        for i in range(week_len):
            date += 1
            if week_exam is week:
                if week_exam is 1 and Days[7-week_len+i] == day:
                    return prettydate(year,month,date)
                if Days[i] is day:
                    return prettydate(year,month,date)

In [86]:
year_exam = 2015
month_exam = 12
week_exam = 2
file = str(year_exam)+"_"+str(month_exam)+"m_"+str(week_exam)+"w.csv"
data = pd.read_excel(file)
data.columns = data.iloc[0]
data.drop(0,inplace=True)
df = data[data['기준년도']=='발생건수']
del df['기준년도']
del df['합계']
df = df.T
df.columns = df.iloc[1]
df.drop('도로형태대구분',inplace=True)
df.drop('도로형태',inplace=True)
del df['합계']
del df['기타']
df = df.reset_index()
df.insert(0,'날짜',10)
tmp = list(df.columns)
tmp[1] = '요일구분'
df.columns = tmp
for day in Days:
    df.loc[df['요일구분']==day,'날짜'] = day2date(year_exam,month_exam,week_exam,day)

In [103]:
data.head()

0 도로형태대구분 도로형태    기준년도     합계   일요일   월요일   화요일   수요일
1      합계   합계    발생건수  12168  1920  3475  3219  3554
2      합계   합계  구성비(%)    100  15.8  28.6  26.5  29.2
3      합계   합계    사망자수     58    11    16    15    16
4      합계   합계  구성비(%)    100    19  27.6  25.9  27.6
5      합계   합계    부상자수  19195  3406  5244  4948  5597

In [98]:
result = []
del result
year_exam = 2014
month_exam = 0
for month in Week_2014:
    week_exam = 0
    month_exam += 1
    for week_len in month:
        week_exam += 1
        
        file = str(year_exam)+"_"+str(month_exam)+"m_"+str(week_exam)+"w.csv"
        print(file, week_len)
        data = pd.read_excel(file)
        data.columns = data.iloc[0]
        data.drop(0,inplace=True)
        df = data[data['기준년도']=='발생건수']
        del df['기준년도']
        del df['합계']
        df = df.T
        df.columns = df.iloc[1]
        df.drop('도로형태대구분',inplace=True)
        df.drop('도로형태',inplace=True)
        del df['합계']
        del df['기타']
        df = df.reset_index()
        df.insert(0,'날짜',10)
        tmp = list(df.columns)
        tmp[1] = '요일구분'
        df.columns = tmp
        for day in Days:
            df.loc[df['요일구분']==day,'날짜'] = day2date(year_exam,month_exam,week_exam,day)
        if df.shape[0] != week_len:
            print('으아앙 달라')
            break
        if 'result' in locals():
            result = pd.merge(result,df,how='outer')
        else:
            result = df.copy()

2014_1m_1w.csv 4
2014_1m_2w.csv 7
2014_1m_3w.csv 7
2014_1m_4w.csv 7
2014_1m_5w.csv 6
2014_2m_1w.csv 1
2014_2m_2w.csv 7
2014_2m_3w.csv 7
2014_2m_4w.csv 7
2014_2m_5w.csv 6
2014_3m_1w.csv 1
2014_3m_2w.csv 7
2014_3m_3w.csv 7
2014_3m_4w.csv 7
2014_3m_5w.csv 7
2014_3m_6w.csv 2
2014_4m_1w.csv 5
2014_4m_2w.csv 7
2014_4m_3w.csv 7
2014_4m_4w.csv 7
2014_4m_5w.csv 4
2014_5m_1w.csv 3
2014_5m_2w.csv 7
2014_5m_3w.csv 7
2014_5m_4w.csv 7
2014_5m_5w.csv 7
2014_6m_1w.csv 7
2014_6m_2w.csv 7
2014_6m_3w.csv 7
2014_6m_4w.csv 7
2014_6m_5w.csv 2
2014_7m_1w.csv 5
2014_7m_2w.csv 7
2014_7m_3w.csv 7
2014_7m_4w.csv 7
2014_7m_5w.csv 5
2014_8m_1w.csv 2
2014_8m_2w.csv 7
2014_8m_3w.csv 7
2014_8m_4w.csv 7
2014_8m_5w.csv 7
2014_8m_6w.csv 1
2014_9m_1w.csv 6
2014_9m_2w.csv 7
2014_9m_3w.csv 7
2014_9m_4w.csv 7
2014_9m_5w.csv 3
2014_10m_1w.csv 4
2014_10m_2w.csv 7
2014_10m_3w.csv 7
2014_10m_4w.csv 7
2014_10m_5w.csv 6
2014_11m_1w.csv 1
2014_11m_2w.csv 7
2014_11m_3w.csv 7
2014_11m_4w.csv 7
2014_11m_5w.csv 7
2014_11m_6w.csv 1
2014_12m_1w.csv 6
2014_12m_2w.csv 7
2014_12m_3w.csv 7
2014_12m_4w.csv 7
2014_12m_5w.csv 4

In [101]:
save("2014년 도로형태",result)

In [99]:
result.shape

(365, 9)

In [100]:
result

           날짜 요일구분 교차로안 교차로부근 횡단보도상 횡단보도부근 터널  교량 철길건널목
0    20140101  수요일  235    76    11      4  -   2   NaN
1    20140102  목요일  266    81    17      7  1   3   NaN
2    20140103  금요일  249   102    29      1  -   2   NaN
3    20140104  토요일  266    95    13      3  2   -   NaN
4    20140105  일요일  192    62    16      7  1   1   NaN
5    20140106  월요일  284    99    19      5  1   2   NaN
6    20140107  화요일  264    84    16     11  1   4   NaN
7    20140108  수요일  296    85    16      5  1   1   NaN
8    20140109  목요일  266    91    16      5  1   2   NaN
9    20140110  금요일  253    93    24      7  1   3   NaN
10   20140111  토요일  264    99    17      4  3   3   NaN
11   20140112  일요일  206    58    12      3  1   2     -
12   20140113  월요일  288    86    20      4  2   3     -
13   20140114  화요일  254   103    20      4  1   2     -
14   20140115  수요일  283   113    16      3  1   3     -
15   20140116  목요일  275   102    15      2  2   2     1
16   20140117  금요일  316   106    21      7  1   2     -
17   20140118  토요일  266   109    11      4  2   1     -
18   20140119  일요일  236    67     7      9  3   2   NaN
19   20140120  월요일  391   121    17      2  2   6   NaN
20   20140121  화요일  326   108    20      9  2   5   NaN
21   20140122  수요일  325   111    23      7  3   5   NaN
22   20140123  목요일  335   121    24     11  1   4   NaN
23   20140124  금요일  360   133    21     15  1   5   NaN
24   20140125  토요일  285   119    25      5  1   2   NaN
25   20140126  일요일  215    71    17      7  2   2     1
26   20140127  월요일  321   122    20      4  -   4     -
27   20140128  화요일  408   110    21     10  3   3     -
28   20140129  수요일  349   113    30      5  1   3     1
29   20140130  목요일  206    71     9      1  2   4     1
..        ...  ...  ...   ...   ...    ... ..  ..   ...
335  20141202  화요일  294    83    22      5  1  12   NaN
336  20141203  수요일  319   116    20      6  1  11   NaN
337  20141204  목요일  343   117    22      2  2   7   NaN
338  20141205  금요일  380   129    18      8  -   3   NaN
339  20141206  토요일  341   135    20      5  1   6   NaN
340  20141207  일요일  245    89    15      2  1   2     1
341  20141208  월요일  399   133    12      5  2   5     -
342  20141209  화요일  339   114    28      6  -   3     -
343  20141210  수요일  339   135    17      9  1   6     -
344  20141211  목요일  288    89    30      8  -   1     -
345  20141212  금요일  340   136    25      3  2   1     -
346  20141213  토요일  329   117    23      5  6  12     -
347  20141214  일요일  213    81    17      6  1   2     -
348  20141215  월요일  316   128    33     14  2   5     -
349  20141216  화요일  308   109    19      5  2   3     -
350  20141217  수요일  296   102    26      9  2   3     -
351  20141218  목요일  273   113    24      8  1   5     1
352  20141219  금요일  319   115    23      9  3   2     -
353  20141220  토요일  324   120    19      6  5  14     -
354  20141221  일요일  228    84     9      3  3   1     -
355  20141222  월요일  262   117    25      8  1   3     -
356  20141223  화요일  316   108    22      8  2   6     -
357  20141224  수요일  326   122    18      4  6   5     1
358  20141225  목요일  222    73     9      7  1   3     -
359  20141226  금요일  332   109    30     10  1   5     -
360  20141227  토요일  263   108    26      4  2   5     -
361  20141228  일요일  179    76    12      1  1   1     -
362  20141229  월요일  284   105    14      6  -   6     -
363  20141230  화요일  327   138    18      5  2   2     -
364  20141231  수요일  326   117    23      3  3   5     1

[365 rows x 9 columns]

In [205]:
df.head()

,요일구분,기준년도,2014년,2014년.1,2014년.2,2014년.3,2014년.4,2014년.5,2014년.6,2014년.7,2014년.8
0,요일구분,기준년도,합계,20세이하,21세이상~30세이하,31세이상~40세이하,41세이상~50세이하,51세이상~60세이하,61세이상~64세이하,65세이상,미분류
8,수요일,발생건수,2017,103,328,420,444,372,81,100,169
9,수요일,구성비(%),100,5.1,16.3,20.8,22,18.4,4,5,8.4
10,수요일,사망자수,17,0,4,5,1,4,1,2,0
11,수요일,부상자수,4087,191,684,867,965,692,147,149,392

In [201]:
df.loc[df['요일구분']=='','날짜'] = 3